version: '3.9'

services:
  huntask-identity-service:
    build:
      context: services/Huntask.Identity.Service/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__HuntaskDbConnection
      - HUNTASK_IDENTITY_SERVICE_HTTP_PORT
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Identity.Service
    depends_on:
      - huntask-db
    volumes:
      - ./logs/Huntask.Identity.Service:/app/logs
    networks:
      - backend

  huntask-tasks-service:
    build:
      context: services/Huntask.Tasks.Service/
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__HuntaskDbConnection
      - HUNTASK_TASKS_SERVICE_HTTP_PORT
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Tasks.Service
    depends_on:
      - huntask-db
      - huntask-identity-service
    volumes:
      - ./logs/Huntask.Tasks.Service:/app/logs
    networks:
      - backend

  huntask-assets-service:
    build:
      context: services/Huntask.Assets.Service/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - HUNTASK_ASSETS_SERVICE_HTTP_PORT
      - ConnectionStrings__HuntaskDbConnection
      - Assets__Folder
      - Assets__DefaultContainer
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Assets.Service
    depends_on:
      - huntask-db
    volumes:
      - ./logs/Huntask.Assets.Service:/app/logs
      - ./assets:/app/assets
    networks:
      - backend

  huntask-client:
    build:
      context: huntask-client
      dockerfile: Dockerfile
    profiles:
      - fe
    ports:
      - "4000:4000"
    networks:
      - backend

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - fe
      - be
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  huntask-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    profiles:
      - db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    profiles:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - huntask-db
    networks:
      - backend

volumes:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  backend:
    driver: bridge