version: '3.9'

services:
  huntask-identity-service:
    build:
      context: services/Huntask.Identity.Service/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__HuntaskDbConnection
      - HuntaskPorts__IdentityServiceHttp
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Cors__AllowOrigins
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Identity.Service
      - FileSizes__MaxAssetFileSize
      - FileSizes__MessageDataThresholdSize
      - FileSizes__MaxAvatarFileSize
      - RabbitMQ__Host
      - RabbitMQ__User
      - RabbitMQ__Password
      - MassTransit__TempDataDirectory
    depends_on:
      huntask-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/Huntask.Identity.Service:/app/logs
      - ./temp/ms-message-data:/app/ms-message-data
    networks:
      - backend

  huntask-tasks-service:
    build:
      context: services/Huntask.Tasks.Service/
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__HuntaskDbConnection
      - HuntaskPorts__TasksServiceHttp
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Cors__AllowOrigins
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Tasks.Service
      - FileSizes__MaxAssetFileSize
      - FileSizes__MessageDataThresholdSize
      - FileSizes__MaxAvatarFileSize
    depends_on:
      huntask-db:
        condition: service_healthy
      huntask-identity-service:
        condition: service_started
    volumes:
      - ./logs/Huntask.Tasks.Service:/app/logs
    networks:
      - backend

  huntask-assets-service:
    build:
      context: services/Huntask.Assets.Service/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    profiles:
      - be
    environment:
      - ASPNETCORE_ENVIRONMENT
      - HuntaskPorts__AssetsServiceHttp
      - ConnectionStrings__HuntaskDbConnection
      - Assets__Folder
      - Assets__DefaultContainer
      - Jwt__Issuer
      - Jwt__Audience
      - Jwt__Secret
      - Jwt__ValidityHours
      - Cors__AllowOrigins
      - Serilog__MinimumLevel__EntityFrameworkCore
      - Serilog__MinimumLevel__Npgsql
      - Serilog__MinimumLevel__Huntask.Assets.Service
      - FileSizes__MaxAssetFileSize
      - FileSizes__MessageDataThresholdSize
      - FileSizes__MaxAvatarFileSize
      - RabbitMQ__Host
      - RabbitMQ__User
      - RabbitMQ__Password
      - MassTransit__TempDataDirectory
    depends_on:
      huntask-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      huntask-identity-service:
        condition: service_started
    volumes:
      - ./logs/Huntask.Assets.Service:/app/logs
      - ./assets:/app/assets
      - ./temp/ms-message-data:/app/ms-message-data
    networks:
      - backend

  huntask-client:
    build:
      context: huntask-client
      dockerfile: Dockerfile
    profiles:
      - fe
    ports:
      - "4000:4000"
    networks:
      - backend

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - fe
      - be
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__User}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password}
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - infra
    depends_on:
      huntask-db:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 40s

  huntask-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${Postgres__User}
      POSTGRES_PASSWORD: ${Postgres__Password}
      POSTGRES_DB: ${Postgres__Db}
    profiles:
      - infra
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d \"$$POSTGRES_DB\" -U \"$$POSTGRES_USER\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    profiles:
      - infra
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PgAdmin__DefaultEmail}
      PGADMIN_DEFAULT_PASSWORD: ${PgAdmin__DefaultPassword}
    depends_on:
      huntask-db:
        condition: service_healthy
    networks:
      - backend

volumes:
  pg_data:
  caddy_data:
  caddy_config:

networks:
  backend:
    driver: bridge