global using Serilog;
global using MediatR;
global using System.Diagnostics.CodeAnalysis;
global using Microsoft.AspNetCore.Mvc;
global using FluentResults;
global using Huntask.Common.Presentation.Controllers;
global using Huntask.Common.Infrastructure.Models.Options;
global using Huntask.Common.Application;
global using Huntask.Common.Presentation.Extensions;
global using static Huntask.Common.Constants;