FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY Huntask.Common/. ../Huntask.Common/
RUN dotnet restore ../Huntask.Common/Huntask.Common.csproj --configfile ../Huntask.Common/nuget.local.config

COPY services/Huntask.Identity.Service/. .
RUN dotnet publish Huntask.Identity.Service.csproj -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

# RUN apt-get update \
#   && apt-get install -y unzip curl \
#   && mkdir -p /vsdbg \
#   && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

# COPY .vsdbg/debug-entry /vsdbg/debug-entry
# RUN chmod +x /vsdbg/debug-entry

EXPOSE 8080
EXPOSE 5005

ENTRYPOINT ["dotnet", "Huntask.Identity.Service.dll"]