FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish Huntask.Tasks.Service.csproj -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

RUN apt-get update \
  && apt-get install -y unzip curl \
  && mkdir -p /vsdbg \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

COPY .vsdbg/debug-entry /vsdbg/debug-entry
RUN chmod +x /vsdbg/debug-entry

EXPOSE 8080
EXPOSE 5005

ENTRYPOINT ["dotnet", "Huntask.Tasks.Service.dll"]