FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY packages/Huntask.Common/ ./packages/Huntask.Common/
COPY services/Huntask.Assets.Service/Huntask.Assets.Service.sln .
COPY services/Huntask.Assets.Service/src/Huntask.Assets.Service/*.csproj ./src/Huntask.Assets.Service/
COPY services/Huntask.Assets.Service/src/Huntask.Assets.Service.Presentation/*.csproj ./src/Huntask.Assets.Service.Presentation/
RUN dotnet restore Huntask.Assets.Service.sln -p:DockerBuild=true

COPY services/Huntask.Assets.Service/src/Huntask.Assets.Service/ ./src/Huntask.Assets.Service/
COPY services/Huntask.Assets.Service/src/Huntask.Assets.Service.Presentation/ ./src/Huntask.Assets.Service.Presentation/
RUN dotnet publish src/Huntask.Assets.Service.Presentation/Huntask.Assets.Service.Presentation.csproj -c Debug -o out -p:DockerBuild=true

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

RUN apt-get update \
  && apt-get install -y unzip curl \
  && mkdir -p /vsdbg \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 8080
EXPOSE 5005

ENTRYPOINT ["dotnet", "Huntask.Assets.Service.Presentation.dll"]