name: 🚀 Docker Compose Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run_docker_compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      # Use debug version of Dockerfile for now
      # As it's still monorepo, should be uncommented
      # when Huntask.Common will be published to NuGet
      # - name: Run Docker Compose
      #   run: |
      #     npm run docker:build
      #     npm run docker:run:detach

      - name: Run Docker Compose
        run: |
          npm run docker:build:debug
          npm run docker:run:debug:detach

      - name: Verify if services are running
        run: docker compose ps

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
